Merge com a implementação de Movimentações Bancárias
MaiconFI/Hiper.Academia.Asp.Net.Core pull request #4
Opened 2019-11-16 01:45 UTC by jeancasulo

2019-11-16 22:37 UTC, MaiconFI requested changes

2019-11-16 22:37 UTC, MaiconFI commented on Hiper.Academia.AspNetCore.Domain/MovimentacoesBancarias/MovimentacaoBancaria.cs
> +            if (valor == default)
Opa. Então deve ser <=

2019-11-16 22:37 UTC, MaiconFI commented on Hiper.Academia.AspNetCore.Services/MovimentacoesBancarias/MovimentacaoBancariaServices.cs
> +        public async Task<ICollection<MovimentacaoBancaria>> GetMovimentacoesAsync(Guid contaBancariaIdExterno)
Pode acessar direto o repositório.

2019-11-16 22:37 UTC, MaiconFI commented on Hiper.Academia.AspNetCore.Services/MovimentacoesBancarias/IMovimentacaoBancariaServices.cs
> +        Task<ICollection<MovimentacaoBancaria>> GetMovimentacoesAsync(Guid contaBancariaIdExterno);
Pode acessar direto o repositório.

2019-11-16 22:37 UTC, MaiconFI commented on Hiper.Academia.AspNetCore.Services/ContasBancarias/ContaBancariaServices.cs
> +        public async Task<ContaBancaria> GetContaBancariaLogadaAsync()
Pode acessar direto o repositório.

2019-11-16 22:37 UTC, MaiconFI commented on Hiper.Academia.AspNetCore.Services/ContasBancarias/IContaBancariaServices.cs
> +        Task<ContaBancaria> GetContaBancariaLogadaAsync();
Pode acessar direto o repositório.

2019-11-16 22:37 UTC, MaiconFI commented on Hiper.Academia.AspNetCore.Repositories/ContasBancarias/IContaBancariaRepository.cs
> +        Task<ContaBancaria> GetContaBancariaLogadaAsync();
O nome do método poderia ser GetContaBancariaPadraoAsync

2019-11-16 22:37 UTC, MaiconFI commented on Hiper.Academia.AspNetCore.Repositories/ContasBancarias/ContaBancariaRepository.cs
> +        public async Task<ContaBancaria> GetContaBancariaLogadaAsync()
O nome do método poderia ser GetContaBancariaPadraoAsync

2019-11-16 22:37 UTC, MaiconFI commented on Hiper.Academia.AspNetCore.Dtos/MovimentacoesBancarias/MovimentacaoBancariaDto.cs
> +        public bool IsEntrada { get; set; }
Criar duas propriedades:
- IsDeposito
- IsSaque

2019-11-16 22:37 UTC, MaiconFI commented on Hiper.Academia.AspNetCore.Web/Controllers/ContaController.cs
> +        private async Task<Guid> GetContaBancariaIdLogada()
Chamar repositório

2019-11-16 22:37 UTC, MaiconFI commented on Hiper.Academia.AspNetCore.Web/Controllers/ContaController.cs
> +            var movimentacoes = _mapper.Map<ICollection<MovimentacaoBancariaDto>>(await _movimentacaoBancariaServices.GetMovimentacoesAsync(contaBancariaId));
Ficou estranho fazer o mapeamento de depois criar um view model na mão.

2019-11-16 22:37 UTC, MaiconFI commented on Hiper.Academia.AspNetCore.Web/Mappers/Converters/Operacoes/OperacaoViewModelConverter.cs
> +    public class MovimentacaoBancariaDtoConverter : ITypeConverter<MovimentacaoBancaria, MovimentacaoBancariaDto>
Deixar nome classe MovimentacaoBancariaToMovimentacaoBancariaDtoConverter.
Renomear arquivo para o nome correto.

2019-11-16 22:37 UTC, MaiconFI commented on Hiper.Academia.AspNetCore.Web/Startup.cs
> +            services.AddSingleton(new MapperConfiguration(x => { x.AddProfile(new HiperAcademiaProfile()); }).CreateMapper());
Acredito que da seguinte forma fica mais fácil de entender:

    var mappingConfig = new MapperConfiguration(mc =>
    {
        mc.AddProfile(new MappingProfile());
    });

    IMapper mapper = mappingConfig.CreateMapper();
    services.AddSingleton(mapper);

2019-11-17 09:41 UTC, jeancasulo commented on Hiper.Academia.AspNetCore.Domain/MovimentacoesBancarias/MovimentacaoBancaria.cs
> +            if (valor == default)
feito

2019-11-17 09:53 UTC, jeancasulo commented on Hiper.Academia.AspNetCore.Services/MovimentacoesBancarias/MovimentacaoBancariaServices.cs
> +        public async Task<ICollection<MovimentacaoBancaria>> GetMovimentacoesAsync(Guid contaBancariaIdExterno)
feito

2019-11-17 09:55 UTC, jeancasulo commented on Hiper.Academia.AspNetCore.Services/MovimentacoesBancarias/IMovimentacaoBancariaServices.cs
> +        Task<ICollection<MovimentacaoBancaria>> GetMovimentacoesAsync(Guid contaBancariaIdExterno);
feito

2019-11-17 09:56 UTC, jeancasulo commented on Hiper.Academia.AspNetCore.Services/ContasBancarias/ContaBancariaServices.cs
> +        public async Task<ContaBancaria> GetContaBancariaLogadaAsync()
feito

2019-11-17 09:56 UTC, jeancasulo commented on Hiper.Academia.AspNetCore.Services/ContasBancarias/IContaBancariaServices.cs
> +        Task<ContaBancaria> GetContaBancariaLogadaAsync();
feito

2019-11-17 09:56 UTC, jeancasulo commented on Hiper.Academia.AspNetCore.Repositories/ContasBancarias/IContaBancariaRepository.cs
> +        Task<ContaBancaria> GetContaBancariaLogadaAsync();
feito

2019-11-17 09:56 UTC, jeancasulo commented on Hiper.Academia.AspNetCore.Repositories/ContasBancarias/ContaBancariaRepository.cs
> +        public async Task<ContaBancaria> GetContaBancariaLogadaAsync()
feito

2019-11-17 09:57 UTC, jeancasulo commented on Hiper.Academia.AspNetCore.Dtos/MovimentacoesBancarias/MovimentacaoBancariaDto.cs
> +        public bool IsEntrada { get; set; }
feito

2019-11-17 10:00 UTC, jeancasulo commented on Hiper.Academia.AspNetCore.Web/Controllers/ContaController.cs
> +        private async Task<Guid> GetContaBancariaIdLogada()
vamos conversar sobre isso

2019-11-17 10:01 UTC, jeancasulo commented on Hiper.Academia.AspNetCore.Web/Controllers/ContaController.cs
> +            var movimentacoes = _mapper.Map<ICollection<MovimentacaoBancariaDto>>(await _movimentacaoBancariaServices.GetMovimentacoesAsync(contaBancariaId));
Por que?

2019-11-17 10:02 UTC, jeancasulo commented on Hiper.Academia.AspNetCore.Web/Mappers/Converters/Operacoes/OperacaoViewModelConverter.cs
> +    public class MovimentacaoBancariaDtoConverter : ITypeConverter<MovimentacaoBancaria, MovimentacaoBancariaDto>
Ok

2019-11-17 10:03 UTC, jeancasulo commented on Hiper.Academia.AspNetCore.Web/Startup.cs
> +            services.AddSingleton(new MapperConfiguration(x => { x.AddProfile(new HiperAcademiaProfile()); }).CreateMapper());
feito

2019-11-18 15:24 UTC, MaiconFI approved these changes

2019-11-18 15:24 UTC, merged